name: Generate README bits
on:
  schedule:
    - cron: "* */24 * * *"
  workflow_dispatch:
jobs:
  build:
    name: Job to update README data
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@master
        id: snake-gif

        with:
          github_user_name: joshdavenport
          svg_out_path: dist/github-contribution-grid-snake.svg
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
